import type { Metadata } from "next";
import "./../globals.css";
import "react-toastify/dist/ReactToastify.css";
import { SidebarMenu } from "@/components/Sidebar/Sidebar";
import { TopNavbar } from "@/components/TopNavbar/TopNavbar";
import { DesignerContextProvider } from "@/contexts/DesignerContext";

export const metadata: Metadata = {
  title: "GBD - Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DesignerContextProvider>
      <main className="flex flex-1 max-w-screen h-screen tw-flex-row bg-gray-100 ">

        <SidebarMenu />

        <div className="w-full h-screen bg-gray-200 gap-4">


          <div className="p-4 h-full w-full">
            {children}
          </div>


        </div>

      </main>
    </DesignerContextProvider>
  );
}
