export enum STORE {
	AUTH_STORE = 'AUTH_STORE',
}

export enum QUERY {
	TABLE_LIST = 'TABLE_LIST',
	COLUMN_FIND_MANY_BY_TABLE_ID = 'COLUMN_FIND_MANY_BY_TABLE_ID',
	TABLE_SHOW = 'TABLE_SHOW',
	COLUMN_SHOW = 'COLUMN_SHOW',
	ROW_SHOW = 'ROW_SHOW',
	ROW_FIND_MANY = 'ROW_FIND_MANY',
	USER_LIST = 'USER_LIST',
	USER_PROFILE = 'USER_PROFILE',
}

export enum COLUMN_TYPE {
	EMPTY = '',
	SHORT_TEXT = 'SHORT_TEXT',
	LONG_TEXT = 'LONG_TEXT',
	DROPDOWN = 'DROPDOWN',
	// FILE = 'FILE',
	DATE = 'DATE',
	RELATIONAL = 'RELATIONAL',
	MULTIRELATIONAL = 'MULTIRELATIONAL',
}

export enum COLUMN_FORMAT {
	// SHORT_TEXT
	ALPHANUMERIC = 'ALPHANUMERIC',
	INTEGER = 'INTEGER',
	DECIMAL = 'DECIMAL',
	URL = 'URL',

	// DATE
	'DD/MM/AAAA' = 'DD/MM/AAAA',
	'MM/DD/AAAA' = 'MM/DD/AAAA',
	'AAAA/MM/DD' = 'AAAA/MM/DD',
	'DD/MM/AAAA hh:mm:ss' = 'DD/MM/AAAA hh:mm:ss',
	'MM/DD/AAAA hh:mm:ss' = 'MM/DD/AAAA hh:mm:ss',
	'AAAA/MM/DD hh:mm:ss' = 'AAAA/MM/DD hh:mm:ss',
	'DD-MM-AAAA' = 'DD-MM-AAAA',
	'MM-DD-AAAA' = 'MM-DD-AAAA',
	'AAAA-MM-DD' = 'AAAA-MM-DD',
	'DD-MM-AAAA hh:mm:ss' = 'DD-MM-AAAA hh:mm:ss',
	'MM-DD-AAAA hh:mm:ss' = 'MM-DD-AAAA hh:mm:ss',
	'AAAA-MM-DD hh:mm:ss' = 'AAAA-MM-DD hh:mm:ss',
}
