export enum STORE {
	AUTH_STORE = 'AUTH_STORE',
}

export enum QUERY {
	TABLE_LIST = 'TABLE_LIST',
	COLUMN_FIND_MANY_BY_TABLE_ID = 'COLUMN_FIND_MANY_BY_TABLE_ID',
	TABLE_SHOW = 'TABLE_SHOW',
	COLUMN_SHOW = 'COLUMN_SHOW',
	ROW_SHOW = 'ROW_SHOW',
}

export enum COLUMN_TYPE {
	EMPTY = '',
	SHORT_TEXT = 'SHORT_TEXT',
	LONG_TEXT = 'LONG_TEXT',
	DROPDOWN = 'DROPDOWN',
	// FILE = 'FILE',
	DATE = 'DATE',
}

export enum COLUMN_FORMAT {
	ALPHANUMERIC = 'ALPHANUMERIC',
	INTEGER = 'INTEGER',
	DECIMAL = 'DECIMAL',
	URL = 'URL',
}
